# park dimensions
PARK_WIDTH  = 80
PARK_HEIGHT = 40
MAX_GUESTS  = 200
TICK_RATE   = 0.1

# finance
STARTING_CASH        = 10000.0
INCOME_TICK_INTERVAL = 150

# build costs
BUILD_COST_PATH    = 10.0
BUILD_COST_RIDE    = 500.0
BUILD_COST_STALL   = 200.0
BUILD_COST_TOILET  = 150.0

# demolish costs
DEMOLISH_COST_PATH    = 5.0
DEMOLISH_COST_RIDE    = 100.0
DEMOLISH_COST_STALL   = 50.0
DEMOLISH_COST_TOILET  = 40.0

# upkeep per 15-second tick
UPKEEP_PER_RIDE    = 25.0
UPKEEP_PER_STALL   = 10.0
UPKEEP_PER_TOILET  = 8.0

# default prices
ENTRANCE_FEE  = 10.0
RIDE_PRICE    = 5.0
STALL_PRICE   = 3.0

# guest behaviour
SPAWN_RATE               = 0.3
HUNGER_RATE              = 0.005
HUNGER_THRESHOLD         = 0.7
BLADDER_RATE             = 0.002
BLADDER_RATE_AFTER_EATING= 0.005
BLADDER_THRESHOLD        = 0.8
HAPPINESS_EXIT_THRESHOLD = 0.2

# flow field
FLOW_FIELD_INFINITY = float("inf")