# park dimensions
PARK_WIDTH  = 80
PARK_HEIGHT = 40
MAX_GUESTS  = 200
TICK_RATE   = 0.1

# finance
STARTING_CASH        = 10000.0
INCOME_TICK_INTERVAL = 150

# build costs
BUILD_COST_PATH    = 25.0
BUILD_COST_RIDE    = 850.0
BUILD_COST_STALL   = 330.0
BUILD_COST_TOILET  = 150.0

# demolish costs
DEMOLISH_COST_PATH    = 15.0
DEMOLISH_COST_RIDE    = 1000.0
DEMOLISH_COST_STALL   = 150.0
DEMOLISH_COST_TOILET  = 140.0

# upkeep per 15-second tick
UPKEEP_PER_RIDE    = 125.0
UPKEEP_PER_STALL   = 100.0
UPKEEP_PER_TOILET  = 80.0

# default prices
ENTRANCE_FEE  = 10.0
RIDE_PRICE    = 5.0
STALL_PRICE   = 3.0
TOILET_PRICE  = 2.0

# editing price values
PRICE_STEP = 0.25
PRICE_MIN  = 0.0
PRICE_MAX  = 50.0

# guest behaviour
SPAWN_RATE               = 0.3
HUNGER_RATE              = 0.005
HUNGER_THRESHOLD         = 0.7
BLADDER_RATE             = 0.002
BLADDER_RATE_AFTER_EATING= 0.005
BLADDER_THRESHOLD        = 0.8
HAPPINESS_EXIT_THRESHOLD = 0.2

# flow field
FLOW_FIELD_INFINITY = float("inf")